export default {
  LOGGING_IN: 'LOGGING_IN',
  LOG_IN_SUCCESS: 'LOG_IN_SUCCESS',
  LOG_IN_FAILURE: 'LOG_IN_FAILURE',
  LOG_OUT: 'LOG_OUT',

  // Customer
  GETTING_CUSTOMERS: 'GETTING_CUSTOMERS',
  GET_CUSTOMERS_SUCCESS: 'GET_CUSTOMERS_SUCCESS',
  GET_CUSTOMERS_FAILURE: 'GET_CUSTOMERS_FAILURE',

  // Product
  GETTING_PRODUCTS: 'GETTING_PRODUCTS',
  GET_PRODUCTS_SUCCESS: 'GET_PRODUCTS_SUCCESS',
  GET_PRODUCTS_FAILURE: 'GET_PRODUCTS_FAILURE',

  GETTING_REQUESTS: 'GETTING_REQUESTS',
  GET_REQUESTS_SUCCESS: 'GET_REQUESTS_SUCCESS',
  GET_REQUESTS_FAILURE: 'GET_REQUESTS_FAILURE',

  INSERTING_REQUEST: 'INSERTING_REQUEST',
  INSERT_REQUEST_SUCCESS: 'INSERT_REQUEST_SUCCESS',
  INSERT_REQUEST_FAILURE: 'INSERT_REQUEST_FAILURE',

  UPDATING_REQUEST: 'UPDATING_REQUEST',
  UPDATE_REQUEST_SUCCESS: 'UPDATE_REQUEST_SUCCESS',
  UPDATE_REQUEST_FAILURE: 'UPDATE_REQUEST_FAILURE',

  DELETING_REQUEST: 'DELETING_REQUEST',
  DELETE_REQUEST_SUCCESS: 'DELETE_REQUEST_SUCCESS',
  DELETE_REQUEST_FAILURE: 'DELETE_REQUEST_FAILURE',

  // Invoice
  GETTING_INVOICES: 'GETTING_INVOICES',
  GET_INVOICES_SUCCESS: 'GET_INVOICES_SUCCESS',
  GET_INVOICES_FAILURE: 'GET_INVOICES_FAILURE',

  GETTING_INVOICE_BY_ID: 'GETTING_INVOICE_BY_ID',
  GET_INVOICE_BY_ID_SUCCESS: 'GET_INVOICE_BY_ID_SUCCESS',
  GET_INVOICE_BY_ID_FAILURE: 'GET_INVOICE_BY_ID_FAILURE',

  INSERTING_INVOICE: 'INSERTING_INVOICE',
  INSERT_INVOICE_SUCCESS: 'INSERT_INVOICE_SUCCESS',
  INSERT_INVOICE_FAILURE: 'INSERT_INVOICE_FAILURE',

  UPDATING_INVOICE: 'UPDATING_INVOICE',
  UPDATE_INVOICE_SUCCESS: 'UPDATE_INVOICE_SUCCESS',
  UPDATE_INVOICE_FAILURE: 'UPDATE_INVOICE_FAILURE',

  // Order
  ADD_ITEM: 'ADD_ITEM',
  SAVE_CUSTOMER_INFO: 'SAVE_CUSTOMER_INFO',
  SAVE_CUSTOMER_ERROR: 'SAVE_CUSTOMER_ERROR',

  SET_ORDER: 'SET_ORDER',
};
